### PR TITLE
Add leading zero to Chapters 1-9

### PR DESCRIPTION
**Pull request by mkatychev**
This will make the chapters show up in order.

### CODE REVIEW

**Comment by below** [comment]
I had kept the Chapter numbers from the original source, but given they all contain zip files anyhow, diff'ing that will be work anyways.
So thanks for your improvement

**Comment by mkatychev** [comment]
@below Could you symlink them in a gitignored directory?

**Comment by below** [comment]
> @below Could you symlink them in a gitignored directory?

I guess I could, but I should probably rather rebase the repository so that you have a direct original-to-modification diff. I had started this repo when I was still figuring stuff out.

**Comment by mkatychev** [comment]
The effort is greatly appreciated, works out of the box!

**Pull request merged**
